KLASNYI_3/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from post import search, search2

urlpatterns = [
    url(r'^', include('post.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('search.urls')),
    url(r'^s/$', search.search),
    url(r'^search-post/$', search2.search_post),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.EIndexView.as_view(), name='index'),
]

search/urls.py
from django.conf.urls import url

from .views import *

app_name = 'search'
urlpatterns = [
    url(r'^$', Search.as_view()),
    url(r'^1$', SearchTag.as_view()),
    url(r'^hashtag.json$', TagJson.as_view()),
]

post/models.py
from django.db import models

from user.models import User


class Post(models.Model):

    class Meta():
        db_table = 'post'
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['created']

    user = models.ForeignKey(User)
    title = models.CharField("Заголовок", max_length=100)
    text = models.TextField("Текст статьи")
    image = models.ImageField("Изоброжение", upload_to='post/', blank=True)
    created = models.DateTimeField("Создан", auto_now_add=True)
    updated = models.DateTimeField("Обновлено", auto_now=True)
    moder = models.BooleanField("Модерация", default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        try:
            this_record = Post.objects.get(id=self.id)

            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(Post, self).save(*args, **kwargs)


class HashTag(models.Model):

    class Meta():
        db_table = 'Tags'
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    name = models.CharField("Имя", max_length=50, unique=True)
    post = models.ManyToManyField(Post)

    def __str__(self):
        return self.name

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 3,
        # 'cols': 80,
        'class' : 'form-control',
        'placeholder' : 'Write your post here'
    }), max_length = 300)

class SearchForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(attrs={
        'size' : 30,
        'class' : 'form-control search-query',
        'autofocus': 'autofocus',
        'placeholder' : 'text'
    }))

class SearchTagForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(attrs={
        'size' : 30,
        'class' : 'form-control search-tag-query typeahead',
        'id' : 'typeahead',
        'autofocus' : 'autofocus',
        'placeholder': 'start typing...'
    }))

search/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
import json

# Create your views here.
from django.http import HttpResponse
from django.views import View
from post.models import Post, HashTag
from .forms import SearchForm, SearchTagForm



class Search(View):
    """ Search all posts url: 127.0.0.1:8000/search/?q=<q>"""

    def get(self, request):
        form = SearchForm()
        context = {'search' : form}
        return render(request, 'search.html', context)

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            q = form.cleaned_data['q']
            posts = Post.objects.filter(text__icontains=q)
            context = {'q' : q, 'posts' : posts}
            return_str = render_to_string ('part_views/_post_search.html', context)
            return HttpResponse(json.dumps(return_str), content_type='application/json')
        else:
            HttpResponseRedirect("/search/")

class SearchTag(View):
    """ Search tags with autocomplete (live search) """

    def get(self, request):
        form = SearchTagForm()
        context = {'searchtag' : form}
        return render(request, 'search_tags.html', context)

    def post(self,request):
        q = request.POST['q']
        form = SearchTagForm()
        tags = HashTag.objects.filter(name__icontains=q)
        context = {'tags' : tags, 'searchtag' : form}
        return render(request, 'search_tags.html', context)

class TagJson(View):
    """ Search tags with autocomplete (live search) json data"""
    def get(self, request):
        q = request.GET.get('q', '')
        taglist = []
        tags = Post.objects.filter(name__icontains=q)
        for tag in tags:
            new = {'q' : tag.text, 'count' : int(len(tag.post.all()))}
            taglist.append(new)
        return HttpResponse(json.dumps(taglist), content_type="application/json")

templates/search/search_rezults.html
{% extends 'base.html' %}

<div class="col-md-12 column">

    {% for post in posts %}

        <div class="well">
            {{ post.text }}
            <p></p>
            <p>
              <i class="icon-user"></i><a href="/user/{{ post.user }}">{{ post.user }}</a>
              | {{ post.created_date | date:"d/m/Y"}}
              | <a href="#"><i class="glyphicon glyphicon-comment"></i> Comments</a>
              | <a href="#"><i class="glyphicon glyphicon-share-alt"></i> Shares</a>
                {% if post.hashtag_set.all|length > 0 %}
              | <i class="icon-tags"></i> Tags:
                {% for hashtag in post.hashtag_set.all %}
                <a href="#"><span class="label label-info">{{ hashtag }}</span></a>
                {% endfor %}
                {% endif %}
            </p>
        </div>

    {% endfor %}

    {% if not posts %}
        <h3> No posts for this query.</h3>
    {% endif %}

</div>


{#<p>You searched for: <strong>{{ query }}</strong></p>#}
{##}
{#{% if books %}#}
{#    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>#}
{#    <ul>#}
{#        {% for book in books %}#}
{#        <li>{{ book.title }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% else %}#}
{#    <p>No books matched your search criteria.</p>#}
{#{% endif %}#}